# Generated by Django 4.1.3 on 2022-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=2, max_digits=100)),
                ('grade', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
